//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package imagecontentsourcepolicy

import (
	configv1 "github.com/openshift/api/config/v1"
	v1alpha1 "github.com/openshift/api/operator/v1alpha1"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ImageContentSourcePolicy)(nil), (*configv1.ImageDigestMirrorSet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RunOnceDurationConfig_To_runonceduration_RunOnceDurationConfig(a.(*v1alpha1.ImageContentSourcePolicy), b.(*configv1.ImageDigestMirrorSet), scope)
	}); err != nil {
		return err
	}

	return nil
}

func autoConvert_v1_RunOnceDurationConfig_To_runonceduration_RunOnceDurationConfig(in *v1alpha1.ImageContentSourcePolicy, out *configv1.ImageDigestMirrorSet, s conversion.Scope) error {
	// in = a.(*v1alpha1.ImageContentSourcePolicy)
	// out = b.(*configv1.ImageDigestMirrorSet)
	digestMirrors := []configv1.ImageDigestMirrors{}
	for _, repoMirrors := range in.Spec.RepositoryDigestMirrors {
		// digestMirror
		mirrors := []configv1.ImageMirror{}
		for _, m := range repoMirrors.Mirrors {
			mirrors = append(mirrors, configv1.ImageMirror(m))
		}
		digestMirror := configv1.ImageDigestMirrors{
			Source:  repoMirrors.Source,
			Mirrors: mirrors,
		}
		digestMirrors = append(digestMirrors, digestMirror)
	}
	out.Spec.ImageDigestMirrors = digestMirrors
		
	return nil
}

// Convert_v1_RunOnceDurationConfig_To_runonceduration_RunOnceDurationConfig is an autogenerated conversion function.
func Convert_v1_RunOnceDurationConfig_To_runonceduration_RunOnceDurationConfig(in *v1alpha1.ImageContentSourcePolicy, out *configv1.ImageDigestMirrorSet, s conversion.Scope) error {
	return autoConvert_v1_RunOnceDurationConfig_To_runonceduration_RunOnceDurationConfig(in, out, s)
}
