FROM quay.io/harpatil/ocp-build-image:go1.25 AS builder
WORKDIR /go/src/k8s.io/kubernetes
# Copy pre-built binaries and scripts
COPY _output/local/bin/linux/amd64/kube-apiserver \
     _output/local/bin/linux/amd64/kube-controller-manager \
     _output/local/bin/linux/amd64/kube-scheduler \
     _output/local/bin/linux/amd64/kubelet \
     _output/local/bin/linux/amd64/watch-termination \
     _output/local/bin/linux/amd64/k8s-tests-ext \
     /tmp/build/
COPY openshift-hack/images/hyperkube/hyperkube \
     openshift-hack/images/hyperkube/kubensenter \
     /tmp/build/
RUN gzip /tmp/build/k8s-tests-ext

FROM registry.ci.openshift.org/ocp/4.21:base-rhel9
RUN yum install -y --setopt=tsflags=nodocs --setopt=skip_missing_names_on_install=False iproute && yum clean all
COPY --from=builder /tmp/build/* /usr/bin/
LABEL io.k8s.display-name="OpenShift Kubernetes Server Commands" \
      io.k8s.description="OpenShift is a platform for developing, building, and deploying containerized applications." \
      io.openshift.tags="openshift,hyperkube" \
      io.openshift.build.versions="kubernetes=1.35.0-alpha.2"