FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.13 AS builder
WORKDIR /go/src/github.com/openshift/kubernetes
COPY . .
RUN make WHAT=test/e2e/e2e.test
; \
    mkdir -p /tmp/build; \
    cp /go/src/github.com/openshift/origin/_output/local/bin/linux/$(go env GOARCH)/e2e.test /tmp/build/k8s-e2e-tests

FROM registry.svc.ci.openshift.org/ocp/4.2:cli
COPY --from=builder /tmp/build/openshift-tests /usr/bin/
RUN yum install --setopt=tsflags=nodocs -y git gzip util-linux && yum clean all && rm -rf /var/cache/yum/* && \
    git config --system user.name test && \
    git config --system user.email test@test.com && \
    chmod g+w /etc/passwd
LABEL io.k8s.display-name="Kubernetes End-to-End Tests" \
      io.openshift.tags="k8s,tests,e2e"
