# This uses the new rhel-coreos-8 base image
# https://github.com/openshift/enhancements/blob/master/enhancements/ocp-coreos-layering/ocp-coreos-layering.md
FROM centos:stream9 as build
# Sadly rpm-ostree in rhel8 right now doesn't support e.g. `rpm-ostree upgrade openshift-hyperkube`
# in a container https://github.com/coreos/rpm-ostree/issues/4034
RUN dnf -y install dnf-utils && dnf download openshift-hyperkube

# This must be replaced by the CI job, but see also https://issues.redhat.com/browse/ART-4352
FROM registry.ci.openshift.org/rhcos-devel/rhel-coreos-8
COPY --from=build /*.rpm /
RUN rpm -Uvh /*.rpm && rm -f /*.rpm
